### ISSUE TITLE
[Rule change] prefer-moving-to-variable

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#1101] opened 2022-12-09 17:01 UTC
Is it possible to consider the generic types in the rule `prefer-moving-to-variable`?

E.g. when we use [get_it](https://pub.dev/packages/get_it) the rule doesn't work correctly:

```
final a = GetIt.instance<InstanceA>(); // Prefer moving repeated invocations to variable and use it instead
final b = GetIt.instance<InstanceB>(); // Prefer moving repeated invocations to variable and use it instead
```

**Comment by incendial** [comment] 2022-12-09 17:20
Definitely!

**Comment by incendial** [comment] 2022-12-16 12:56
@furaiev hm, I'm unable to reproduce the warning. Could you please create a repro?

**Comment by incendial** [comment] 2022-12-16 13:01
Oh, I copied more from GetIt implementation and the issue appeared, working on the fix.

**Comment by incendial** [comment] 2022-12-16 13:04
This one detail is causing the problem https://github.com/fluttercommunity/get_it/blob/master/lib/get_it_impl.dart#L425

**Comment by incendial** [comment] 2022-12-19 15:48
Fixed in 5.3.0 🚀

**Closed by incendial** 2022-12-19 15:48 UTC
Labels: type: bug, good first issue, waiting for release, area-rules
