### ISSUE TITLE
[Rule change] long-parameters-list - ignore optional prameters

### ISSUE THREAD

**Issue by NaikSoftware** [dart-code-checker/dart-code-metrics#495] opened 2021-10-08 09:10 UTC
Its normal to have 5+ parameters in flutter if only 1..3 required. For example:
![image](https://user-images.githubusercontent.com/4218994/136529842-f8773b25-36f4-4de1-bbd2-e892c66349b1.png)
Typical API request - only 3 parameters required, but we need to have ability to customize some parameters sometimes. 

I think this rule created for avoiding `functionCall(p1, p1, p3...., p5)` but it is not my case.
Without this rule change our team can't use it.

P.S.: especially dart analysis message sounds like _info: Long Parameter List. This method **require** 5 arguments._

**Comment by incendial** [comment] 2022-10-31 19:07
Closing as duplicate of #420

**Closed by incendial** 2022-10-31 19:07 UTC
